# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
# Uncomment to use the .env file
dotenv: .env
#change to true to verify smart contracts
verify: False
# set a custom mnemonic for the development network
networks:
  #set the default deployment network brownie will use
  default: kovan
  #networks
  development:
    keyhash: '0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4'
    fee: 100000000000000000
    jobId: '29fa9aa13bf1468788b7cc4a500a45b8'
    update_interval: 60
    verify: False
  kovan:
    keyhash: '0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4'
    fee: 100000000000000000
    oracle: '0x2f90A6D021db21e1B2A077c5a37B3C7E75D15b7e'
    jobId: '29fa9aa13bf1468788b7cc4a500a45b8'
    # Change to True if you have an Etherscan API key and want to verify
    verify: False
    update_interval: 60
  ganache:
    keyhash: '0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4'
    fee: 100000000000000000
    jobId: '29fa9aa13bf1468788b7cc4a500a45b8'
    update_interval: 60
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
  # could also do from_mnemonic, and you'd have to change the accounts.add to accounts.from_mnemonic
